### PR TITLE
Created server, setup templating and static resources

### PR DESCRIPTION
**Pull request by Blaze349**
This time can you click approve? I'll make sure not to delete any of your work. Thanks!

### CODE REVIEW

**Comment by card100** [comment]
Ahhh!!!  It's grayed out again... :(

I really don't know how to merge this.

**Comment by Blaze349** [comment]
I can merge it if you give me write access. Or I can give you instructions.
You have to open it in an editor. Then it should say

> ">>>>" Blaze349

with my code then 
> "====" 

with the other branch.

Delete duplicate code, then delete those two top things.

**Comment by card100** [comment]
Ok,
Gave you write
https://github.com/gitscratch/gitscratch/invitations

**Comment by Blaze349** [comment]
Thank you. I'll start merging it

**Pull request merged**
