### PR TITLE
Created server, setup templating and static resources

### PR DESCRIPTION
**Pull request by Blaze349**
On scratch you guys decided to use node.js
I've setup the server and stuff.
I'm hoping to do more but I've got to complete an essay

### CODE REVIEW

**Comment by Blaze349** [comment]
Thanks for allowing me to join gitscratch! I will be unable to communicate on the Scratch thread until May 21st but that shouldn't affect anything

**Comment by card100** [comment]
Ok that's fine.  Glad you're helping!

**Comment by card100** [comment]
You can see jobs I put out under the projects tab.  I am going to be working on adding more

**Comment by Blaze349** [comment]
I'll start working on them as soon as my first branch is merged. Now that I am a contributor can I push directly to the main repo?

**Comment by card100** [comment]
Yes.  Just please keep the dots in the url so that Ghpages works.  Thx

**Comment by Blaze349** [comment]
Ok but could you merge my pull request?

**Comment by card100** [comment]
I am having trouble doing so for some reason.  Do you think you could do it manually?

**Comment by Blaze349** [comment]
Ok I know what to do. Reject the pull request and I'll put it in again. Could you add my alt account to the organization @TheOptimusMaximus

**Comment by card100** [comment]
I closed it. ^^^

I will invite your other account.

**Comment by Blaze349** [comment]
Ok thanks

**Pull request closed without merging**
